<?= $this->dashboard(); ?>
<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem;">
      <div class="card-body">


        <div class="row">
          <div class="col">
            <h2>Paciente cadastrado com sucesso</h2><br>

            <h6>Um email foi  enviado ao cliente com as informações de senha e login.</h6>
          </div>
        </div>

        <div class="row">
          <div class="col">
            <a href="/" class="btn btn-primary btn-block">Página Inicial</a>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>



    
  