

<head>




  <!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="vendor/bootstrap/css/bootstrap.min.css">
  <!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="fonts/font-awesome-4.7.0/css/font-awesome.min.css">
  <!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="vendor/animate/animate.css">
  <!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="vendor/css-hamburgers/hamburgers.min.css">
  <!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="vendor/select2/select2.min.css">
  <!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="\css\util.css">
  <link rel="stylesheet" type="text/css" href="\css\main.css">
  <!--===============================================================================================-->
</head>


<body>
<?= $this->dashboard(); ?>

  <div class="limiter">
    <div class="container-login100 ">
      <div class="wrap-login100  ">
        <div class="login100-pic js-tilt" style="margin-top: -100px;" data-tilt>
          <img src="img/img-01.png" alt="IMG">
        </div>

        <form action="" method="post" class="login100-form validate-form" style="margin-top: -56px;">
          <span class="login100-form-title">
           Médico cadastrado com sucesso!
          </span>
          <h5>A senha inicial são os 3 primeiros digitos do cpf.</h5>
          <div class="container-login100-form-btn" style="margin-bottom: 50px;">
            <a href="/" class="btn  btn-block login100-form-btn">Página Inicial</a>
          </div>
      </div>
      </form>
    </div>
  </div>
  </div>




  <!--===============================================================================================-->
  <script src="vendor/jquery/jquery-3.2.1.min.js"></script>
  <!--===============================================================================================-->
  <script src="vendor/bootstrap/js/popper.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.min.js"></script>
  <!--===============================================================================================-->
  <script src="vendor/select2/select2.min.js"></script>
  <!--===============================================================================================-->
  <script src="vendor/tilt/tilt.jquery.min.js"></script>
  <script>
    $('.js-tilt').tilt({
      scale: 1.1
    })
  </script>
  <!--===============================================================================================-->
  <script src="js/main.js"></script>
  <!--<= $this->footer() ?> -->
</body>

