<main class="main-content">
  <section class="slideshow">
    <div class="slideshow-inner">
      <div class="slides">
        <div class="slide is-active ">
          <div class="slide-content">
            <div class="caption">
              <div class="title">Sistema Hospitalar</div>
              <div class="text">
                <p>Tudo de forma digital</p>
              </div>
              <a href="#" class="btn-slide">
                <span class="btn-inner">Saiba mais</span>
              </a>
            </div>
          </div>
          <div class="image-container">
            <img src="\img\slide1.jpg" alt="" class="image" />
          </div>
        </div>
        <div class="slide">
          <div class="slide-content">
            <div class="caption">
              <div class="title">Melhores Planos</div>
              <div class="text">
                <p>Escolha o melhor plano pra vocÊ</p>
              </div>
              <a href="#" class="btn-slide">
                <span class="btn-inner">Saiba mais</span>
              </a>
            </div>
          </div>
          <div class="image-container">
            <img src="\img\slide2.png" alt="" class="image" />
          </div>
        </div>
        <div class="slide">
          <div class="slide-content">
            <div class="caption">
              <div class="title">Health+</div>
              <div class="text">
                <p>Fique por dentro dos principais assuntos de saúde com a nosssa prórpia rede social</p>
              </div>
              <a href="#" class="btn-slide">
                <span class="btn-inner">Saiba mais</span>
              </a>
            </div>
          </div>
          <div class="image-container">
            <img src="\img\slide3.jpg" alt="" class="image" />
          </div>
        </div>
        <div class="pagination">
          <div class="item is-active">
            <span class="icon">1</span>
          </div>
          <div class="item">
            <span class="icon">2</span>
          </div>
          <div class="item">
            <span class="icon">3</span>
          </div>
        </div>
        <div class="arrows">
          <div class="arrow prev">
            <span class="svg svg-arrow-left">
              <svg version="1.1" id="svg4-Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="14px" height="26px" viewBox="0 0 14 26" enable-background="new 0 0 14 26" xml:space="preserve">
                <path d="M13,26c-0.256,0-0.512-0.098-0.707-0.293l-12-12c-0.391-0.391-0.391-1.023,0-1.414l12-12c0.391-0.391,1.023-0.391,1.414,0s0.391,1.023,0,1.414L2.414,13l11.293,11.293c0.391,0.391,0.391,1.023,0,1.414C13.512,25.902,13.256,26,13,26z" />
              </svg>
              <span class="alt sr-only"></span>
            </span>
          </div>
          <div class="arrow next">
            <span class="svg svg-arrow-right">
              <svg version="1.1" id="svg5-Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="14px" height="26px" viewBox="0 0 14 26" enable-background="new 0 0 14 26" xml:space="preserve">
                <path d="M1,0c0.256,0,0.512,0.098,0.707,0.293l12,12c0.391,0.391,0.391,1.023,0,1.414l-12,12c-0.391,0.391-1.023,0.391-1.414,0s-0.391-1.023,0-1.414L11.586,13L0.293,1.707c-0.391-0.391-0.391-1.023,0-1.414C0.488,0.098,0.744,0,1,0z" />
              </svg>
              <span class="alt sr-only"></span>
            </span>
          </div>
        </div>
      </div>
  </section>
</main>
<!-- box verde com incones -->
<div class="container content col-md-6">
  <div class="row">
    <div class="col-md-4 box cart" style=" border-radius: 10px 0px 0px 10px">
      <a href="/leads" class="link">
        <div class="transicao-subir">
          <img class="card-img-top" src="\img\hospital.png" style="width: 50px; margin:20px 20px; " alt="Card image cap">
          <h4 class="title-div">Sobre o Hospital</h4>
          <p>
          <h6 class="text-box">Saiba tudo sobre a nossa rede, proficionais e exames.</h6>
          <div class=" read-more" style="text-align:center;">
            <h6 class="">Leia mais &gt;</h6>
          </div>
        </div>
      </a>
    </div>
    <div class="col-md-4 box cart" style=" border-radius: 0px 0px 0px 0px; background-color:#3796bf;">
      <a href="/leads" class="link">
        <div class="transicao-subir">
          <img class="card-img-top" src="\img\buy.png" style="width: 50px; margin:20px 20px; " alt="Card image cap">

          <h4 class="title-div">Adquira um plano</h4>
          <p>
          <h6 class="text-box">Faça uma simulação e escolha a melhor opção para você!</h6>
          <div class=" read-more" style="text-align:center;">
            <h6 class="">Leia mais &gt;</h6>
          </div>
      </a>
    </div>
  </div>
  <div class="col-md-4 box cart" style=" border-radius: 0px 10px 10px 00px">
    <a href="/leads" class="link">
      <div class="transicao-subir">
        <img class="card-img-top" src="\img\mask.png" style="width: 50px; margin:20px 20px; " alt="Card image cap">
        <h4 class="title-div">Health+</h4>
        <p>
        <h6 class="text-box">Rede social própria para ficar por dentro de tudo sobre saúde</h6>
        <div class=" read-more" style="text-align:center;">
          <h6 class="">Leia mais &gt;</h6>
        </div>
      </div>
    </a>
  </div>
</div>
</div>
<!--users login box -->
<div class="col-md-12 planos-background">
  <div class="row">
    <div class="col-md-12 " style="margin-bottom: 5%">
      <h2 class="text-left title title-div" style="color: #52cbff;">Já possui um cadastro?</h2>
      <hr class="divisor-plano">
      <h5 class="text-left title" style="margin-bottom:40px;">Escolha de acordo com o seu tipo de usuário. </h5>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <div class="feature-box justify-content-center">
        <div class="feature-img align-items-center">
          <img class="" src="/img/admin.png" style="width:40px; margin-top:10px;" alt="Card image cap" />
        </div>
        <a href="/adm" class="btn btn-wihte btn-block mb-2 button-text">ADMINISTRADOR</a>
      </div>
    </div>
    <div class="col-md-4">
      <div class="feature-box justify-content-center">

        <div class="feature-img align-items-center">
          <img class="" src="/img/doctor.png" style="width:40px; margin-top:10px; " alt="" />
        </div>
        <div class="feature-text">
          <a href="/doctor" class="btn btn-wihte btn-block mb-2 button-text">MÉDICO</a>
        </div>
      </div>
    </div>
    <div class="col-md-4 ">
      <div class="feature-box justify-content-center">
        <div class="feature-img align-items-center">
          <img class="" src="/img/patient.png" style="width:40px; margin-top:10px; " />
        </div>
        <div class="feature-text">
          <a href="/patient" class="btn btn-wihte btn-block mb-2 button-text">PACIENTE</a>
        </div>
      </div>
    </div>
  </div>
</div>

<!--Services -->
<div class="col-sm-12 service-background" style="margin-bottom: 5%">
  <div class="row">
    <div class="col-sm-6">
      <div class="card " style=" border: 0px;">
        <div class="card-body" style="background-color: #2f81a5;">
          <div class="row">
            <div class="col-sm-6">
              <div class="card service-detail">
                <div class="card-body service-box">
                <img class="" src="/img/exame.png" style="width:50px; margin-top:10px; " />
                  <h5 class="card-title">Agendamento de exames online</h5>
                  <p class="card-text">Agende seus exames de forma totalmente online, sem burocrácia.</p>
                </div>
              </div>
            </div>
            <div class="col-sm-6">
              <div class="card service-detail">
                <div class="card-body service-box">
                <img class="" src="/img/siren.png" style="width:50px; margin-top:10px; " />
                  <h5 class="card-title">Serviço de Urgencia e Emergência</h5>
                  <p class="card-text">Fornecemos o melhor pronto atendimento da região.</p>
                </div>
              </div>
            </div>

            <div class="col-sm-6">
              <div class="card service-detail">
                <div class="card-body service-box">
                <img class="" src="/img/analysis.png" style="width:50px; margin-top:10px; " />
                  <h5 class="card-title">Consulta fácil de dados</h5>
                  <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                </div>
              </div>
            </div>
            <div class="col-sm-6 ">
              <div class="card service-detail">
                <div class="card-body service-box">
                <img class="" src="/img/social-media.png" style="width:50px; margin-top:10px; " />
                  <h5 class="card-title">Rede Social exclusiva</h5>
                  <p class="card-text ">Para saber novidades e compartilhar suas experiências com outros usuários.</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>


    <div class="col-sm-6">
      <div class="card service-detail" style=" margin-top: 3%;">
        <div class="card-body service-box" >
        <div class="row">
        <div class="col-sm-3" style="padding-right: 55%;">
        <img class="" src="/img/doctor.jpg" style="width:400px; height:360px;  " />
        </div>
        <div class="col-sm-5" style=" padding-top:15%; " >
          <h5 class="card-title">Sobre o Hospital</h5>
          <p class="card-text">Equipe especializada com os melhores médicos e equipamentos, e a facilidade de acesso de tudo digital.</p>
        </div>
        </div>
      </div>
      </div>
    </div>
    </div>
  </div>

</div>

<?= $this->footer() ?>