<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="vendor/animate/animate.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="vendor/select2/select2.min.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="\css\util.css">
<link rel="stylesheet" type="text/css" href="\css\main.css">
<!--===============================================================================================-->
<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card cards-geral " style="width: 30rem;  margin-bottom:10%;  margin-right: 20px">
      <div class="card-body container-plain">
        <div class="card-body  ">
          <div class="row">
            <div class="col-md-12" style="margin-bottom: 0px; ">
              <h2><?= $this->view->plains['name'] ?></h2><br>
              <?php foreach ($this->view->descriptions as $index => $description) : ?>
                <ul class="list-unstyled my-2 text-small text-left font-weight-small">
                  <li class="mb-3">
                    <i class="fa fa-check mr-2 text-white"></i><?= $description['description'] ?>
                  </li>
                </ul>
              <?php endforeach ?>
              <hr style="background-color: white; margin-top: 20%;">
              <h4>Total: R$<?= $this->view->plains['price'] ?></h4><br>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col">


          </div>
        </div>

      </div>
    </div>
    <div class="card cards-geral" style="width: 50rem;  margin-bottom:10%;">
      <div class="card-body">
        <div class="row">
          <div class="col-md-12">

            <h5> Informe seus dados pessoais </h5>
            <hr>
          </div>
        </div>

        <div class="row">
          <div class="col">

            <form action="/register-lead" method="post">

              <input type="hidden" name="id_plan" value="<?= $this->view->id_plains['id'] ?>">



              <div class="row">
                <div class="form-group col-md-6 wrap-input100 validate-input col-md-12">
                  <input type="text" class="input100" value="<?= $this->view->user['name'] ?>" name="name" class="form-control" placeholder="Nome">
                  <span class="focus-input100"></span>
                  <span class="symbol-input100">
                    <i class="fa fa-user" aria-hidden="true"></i>
                  </span>
                </div>

                <div class="form-group col-md-6  wrap-input100 validate-input">
                  <input type="text" class="input100" value="<?= $this->view->user['cpf'] ?>" name="cpf" class="form-control" placeholder="CPF">
                  <span class="focus-input100"></span>
                  <span class="symbol-input100">
                    <i class="fa fa-envelope" aria-hidden="true"></i>
                  </span>
                </div>

                <div class="form-group col-md-6  wrap-input100 validate-input">
                  <input type="text" class="input100" value="<?= $this->view->user['cellphone'] ?>" name="cellphone" class="form-control" placeholder="Telefone">
                  <span class="focus-input100"></span>
                  <span class="symbol-input100">
                    <i class="fa fa-phone" aria-hidden="true"></i>
                  </span>
               
                </div>

                <div class="form-group col-md-6  wrap-input100 validate-input">
                  <input type="text" class="input100" value="<?= $this->view->user['born_register'] ?>" name="born_register" class="form-control" placeholder="Data de nascimento">
                  <span class="focus-input100"></span>
                  <span class="symbol-input100">
                    <i class="fa fa-calendar" aria-hidden="true"></i>
                  </span>
               
                </div>

                <div class="form-group col-md-6  wrap-input100 validate-input">
                  <input type="text" class="input100" value="<?= $this->view->user['born_register'] ?>" name="born_register" class="form-control" placeholder="Gênero">
                
                  <span class="focus-input100"></span>
                  <span class="symbol-input100">
                    <i class="fa fa-transgender" aria-hidden="true"></i>
                  </span>
                </div>

                <div class="col-md-12">
                  <h5> Endereço </h5>
                  <hr>
                </div>
                <div class="form-group col-md-4  wrap-input100 validate-input">
                  <input type="text" class="input100" value="<?= $this->view->user['cep'] ?>" name="cep" class="form-control" placeholder="CEP">
                  <span class="focus-input100"></span>
                  <span class="symbol-input100">
                    <i class="fa fa-map-marker" aria-hidden="true"></i>
                  </span>
                
                </div>

                <div class="form-group col-md-8 wrap-input100 validate-input">
                  <input type="text" class="input100" value="<?= $this->view->user['citty'] ?>" name="citty" class="form-control" placeholder="Cidade">
                  <span class="focus-input100"></span>
                  <span class="symbol-input100">
                    <i class="fa fa-location-arrow" aria-hidden="true"></i>
                  </span>
                
                </div>

                <div class="form-group col-md-4  wrap-input100 validate-input">
                  <input type="text" class="input100" value="<?= $this->view->user['number'] ?>" name="number" class="form-control" placeholder="Número">
                  <span class="focus-input100"></span>
                  <span class="symbol-input100">
                    <i class="fa fa-sort-numeric-asc" aria-hidden="true"></i>
                  </span>
               
                </div>


                <div class="form-group col-md-8  wrap-input100 validate-input">
                  <input type="text" class="input100" value="<?= $this->view->user['street'] ?>" name="street" class="form-control" placeholder="Rua">
                  <span class="focus-input100"></span>
                  <span class="symbol-input100">
                    <i class="fa fa-home" aria-hidden="true"></i>
                  </span>
               
                </div>


                <div class="form-group col-md-6  wrap-input100 validate-input">
                  <input type="text" class="input100" value="<?= $this->view->user['district'] ?>" name="district" class="form-control" placeholder="Bairro">
                  <span class="focus-input100"></span>
                  <span class="symbol-input100">
                    <i class="fa fa-street-view" aria-hidden="true"></i>
                  </span>
                
                </div>

                <div class="col-md-6 center ">
                  <button type="submit" class="btn btn-primary btn-block">Entrar</button>

                </div>

                <?php if ($this->view->registerError) { ?>

                  <small class="form-text text-danger">*Erro ao tentar realizar o cadastro, verifique se os campos foram preenchidos corretamente.</small>
              </div>
            <?php } ?>
            </form>

          </div>
        </div>

      </div>
    </div>
  </div>
</div>