
<?=$this->dashboard_patient();?>


<header>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>


    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>


    


</header>
<style>
    @import url(https://fonts.googleapis.com/css?family=Lato:400,300,700);

    @font-face {
        font-family: dsaribold;
        src: url(../assets/fonts/natal/dsari-bold-DSari.woff2);
    }

    @font-face {
        font-family: dsarimedium;
        src: url(../assets/fonts/natal/dsari-medium-DSari.woff2);
    }

    @page {
        size: A4;
        margin: 0;
        margin-bottom: 0.5cm;
        margin-top: 0.5cm;
    }

    @media print {

        html,
        body {
            width: 190mm;
            height: 297mm;
        }

        h4 {
            font-size: 20px;
        }

        .col-md-4 {
            width: 33%;
            float: left;
        }

        .col-md-12 {
            font-size: 13px;
        }

        .escondido {
            display: none;
        }

        .bgm-green {
            background-color: #00995d !important;
        }

        .emLinhaPrint {
            display: table-cell !important;
        }

        .divEnvio {
            display: none !important;
        }

        .camposEnvio {
            display: none !important;
        }

        .divAceitar {
            display: none !important;
        }

        .divAlterar {
            display: none !important;
        }

        .c-white {
            font-size: 18px;
        }
    }

    textarea {
        margin: 20px;
        width: 96%;
        padding: 5px;
        border: 1px solid #0a5f55;
        margin-left: 0px;
    }

    button {
        background: #00995d;
        color: #fff;
        padding: 10px 20px;
        border-radius: 10px;
        width: 200px;
        font-weight: 600;
    }

    .col-md-6 {
        width: 50%;
        float: left;
        margin-top: -3px;
    }

    button:hover {
        transition: background 1s;
        background: #fff;
        color: #00995d;
    }

    p {
        margin-bottom: 0px;
    }

    .termosadesao {
        margin: 0px 20px 50px;
    }

    .btnEnviar {
        color: #fff;
        font-size: 17px;
        background: #00995d;
        padding: 10px 20px;
        width: 280px;
        border-radius: 8px;
        font-weight: 900;
    }

    .btnEnviar:hover {
        transition: background 1s all;
        color: #00995d;
        opacity: 0.8;
    }

    .caixaPlanos {
        text-align: center;
        border: 1px solid #4CAF50;
        padding: 15px;
        border-radius: 8px;
        text-align: center;
        box-shadow: 0 1px 2px rgba(0, 0, 0, 0.6);
    }

    .form-control {
        border: 1px solid #4CAF50;
    }

    .form-control:focus {
        border-bottom: 2px solid #0a5f55;
    }

    .togInp label {
        display: inline-block;
        padding: 9px 17px !important;
        margin: 13px 0px 0px -3px !important;
        font-weight: 600;
        -webkit-border-radius: 50px;
        -moz-border-radius: 50px;
        border-radius: 50px;
        -webkit-transition: all .8s ease;
        transition: all .8s ease;
    }


    .togInp input[type="radio"] {
        display: none;

    }

    .togInp input:checked+label {
        background: #0a5f55 !important;
        color: white;
    }

    .togInp input[type="radio"].error+label {
        background: #00995d;
        color: white;
    }

    .togInp span.error {
        right: 17px;
        margin-top: -46px;
    }

    .iconDes {
        font-size: 22px;
        margin-left: 1px;
        color: #4CAF50;
        border-radius: 56px;
        padding-top: 0px;
    }


    .overlay {
        position: fixed;
        top: 0;
        bottom: 0;
        left: 0;
        right: 0;
        background: rgba(0, 0, 0, 0.7);
        transition: opacity 500ms;
        visibility: hidden;
        opacity: 0;
    }

    .overlay:target {
        visibility: visible;
        opacity: 1;
    }

    .popup {
        margin: 70px auto;
        padding: 20px;
        background: #fff;
        border-radius: 5px;
        width: 50%;
        height: 50%;
        position: relative;
        transition: all 5s ease-in-out;
    }

    .popup h2 {
        margin-top: 0;
        color: #333;
        font-family: Tahoma, Arial, sans-serif;
    }

    .popup .close {
        position: absolute;
        top: 20px;
        right: 30px;
        transition: all 200ms;
        font-size: 30px;
        font-weight: bold;
        text-decoration: none;
        color: #333;
    }

    .popup .close:hover {
        color: #4CAF50;
    }

    .popup .content {
        max-height: 92%;
        overflow: auto;
    }

    @media screen and (max-width: 700px) {
        .box {
            width: 70%;
        }

        .popup {
            width: 70%;
        }
    }

    @media screen and (min-width: 768px){
	.card .card-body.card-padding {
		padding: 25px 27px;
	}
}
/* GRID */

.gridPage .grid {
    text-align: center;
    /* padding-top: 30px; */
}

div.gridDay {
    /* width: 100px; */
}
div.paging, div.gridDay {
    margin: 0px 2px;
    float: left;
    overflow: hidden;
}
div.gridDay {
    /* width: 120px; */
    font-size: 1em;
}
.gridPage .gridDay {
    text-align: center;
    position: relative;
    margin: 0 !important;
    /* padding-left: 10px; */
    /* padding-right: 10px; */
}
div.gridDay {
    /* max-width: 300px; */
    margin: 0px auto;
}

.gridPage .gridHeader {
    padding: 10px 0;
    border-radius: 3px;
    margin-bottom: 20px;
    margin-left: 2px;
    margin-right: 2px;
    position: relative;
}

.gridPage .gridHeader:after {
    content: '';
    height: 30px;
    width: 1px;
    background: #e4e4e4;
    position: absolute;
    top: 50%;
    margin-top: -15px;
    right: -12px;
}

div.gridDay h4 {
	margin: 0px;
	color: inherit;
    white-space: nowrap;
}

div.gridPage div.gridDay span.gridHeaderDayName {
    font-size: 1.2em;
    text-transform: uppercase;
    color: #666;
    font-weight: 600;
}

div.gridDay span.gridHeaderDayName, div.gridDay span.gridHeaderDate {
    font-weight: normal;
    display: block;
}

span.gridHeaderDayName, span.gridHeaderDate {
    display: none;
}

div.gridPage div.gridDay span.gridHeaderDate, div.gridPage div.gridDay span.gridHeaderFull {
    font-size: 0.85em;
}

div.gridDay span.gridHeaderFull {
    display: none;
}

div.gridPage div.gridDay span.gridHeaderDate, div.gridPage div.gridDay span.gridHeaderFull {
    font-size: 0.85em;
}

.gridPage .gridAgendamentoDia .gridSlot.gridFree a, .gridPage .gridAgendamentoDia .gridSlot.gridHighlight a {
    text-decoration: none;
    color: #00995d;
    position: absolute;
    margin: 0;
    padding: 0;
    top: 50%;
    left: 5%;
    width: 90%;
    z-index: 1;
    cursor: pointer;
    transform: translateY(-50%);
    -webkit-transform: translateY(-50%);
    -ms-transform: translateY(-50%);
}

.gridPage .gridAgendamentoDia .gridSlot {
    font-family: 'Open Sans', 'Helvetica', 'Arial', sans-serif;
    display: block;
    border-radius: 5px;
    background: #fff;
    padding-top: 20px;
    padding-left: 5px;
    padding-right: 5px;
    padding-bottom: 20px;
    margin: 5px auto 0;
    white-space: normal;
    transition: background 0.3s, transform 0.5s;
    -webkit-transition: background 0.3s, -webkit-transform 0.5s;
    position: relative;
    z-index: 2;
    cursor: pointer;
    overflow: hidden;
}

.gridSlot.gridFree:hover {
	background: #00995d;
}

.gridSlot.gridFree:hover > a{
	color: #fff!important;
}

.gridPage .gridAgendamentoDia .gridSlot.gridFree, .gridPage .gridAgendamentoDia .gridSlot.gridHighlight {
    border: 1px solid #00995d;
    cursor: pointer;
}

div.gridSlot {
    padding: 2px;
    margin: 4px 0px;
    white-space: nowrap;
    /* text-align: center; */
}

.gridPage .gridAgendamentoDia .gridSlot.gridBusy {
    border: 1px solid #e4e4e4;
    background: #ffffff;
}

.gridPage .gridAgendamentoDia .gridSlot span {
    text-decoration: none;
    color: #e4e4e4;
    position: absolute;
    margin: 0;
    padding: 0;
    top: 50%;
    left: 5%;
    width: 90%;
    transform: translateY(-50%);
    -webkit-transform: translateY(-50%);
    -ms-transform: translateY(-50%);
}

div.gridBusy, div.gridTechnicallyFree {
    color: #DDD;
    text-decoration: line-through;
}

.gridPage .gridAgendamentoDia .gridSlot.gridHighlight {
    background: #00995d;
}
.gridPage .gridAgendamentoDia .gridSlot.gridFree, .gridPage .gridAgendamentoDia .gridSlot.gridHighlight {
    border: 1px solid #00995d;
    cursor: pointer;
}

div.gridHighlight {
    background-color: #FAEAC3;
}

.gridPage .gridAgendamentoDia .gridSlot.gridHighlight a, .gridPage .gridAgendamentoDia .gridSlot.gridHighlight span {
    color: #ffffff;
    text-decoration: none;
}

.btnDiaSemana {
	align-self: center;
	padding: 20px 10px 18px 10px;
	font-family: arial;
	font-size: 18px;
	letter-spacing: 1px;
	text-transform: uppercase;
	text-align: center;
	background: white;
	color: #00995d;
	border: 1px solid #00995d;
	border-radius: 10px;
	transition: all 0.1s ease-in-out;
	cursor: pointer;
}

.btnDatas {	
	transition: 0.3s;
}

.btnDatas.selected {
	background: #00995d;
 	color: white;
}

.btnDiaSemana:hover{
 background: #00995d;
 color: white;
}

.btnDiaSemana:active{
  transform: scale(1.025);
}

/* .gridHeaderDayName:before {
    content: attr(data-content);
}

.gridHeaderDate:before {
    content: attr(data-content);
} */

#agendamentoUm:before, #agendamentoDois:before, #agendamentoTres:before, #agendamentoQuatro:before, #agendamentoCinco:before {
    content: attr(data-content);
}

.hide {
	display:none;
}

.show {
	display:unset;
}

/*
==============================================
pullDown
==============================================
*/

.confirmarAgendamento {
    padding: 10px 50px;
    border-radius: 39px;
    margin-top: 30px;
}

.pullDown{
	animation-name: pullDown;
	-webkit-animation-name: pullDown;	

	animation-duration: .6s;	
	-webkit-animation-duration: .6s;

	animation-timing-function: ease-out;	
	-webkit-animation-timing-function: ease-out;	

	transform-origin: 50% 0%;
	-ms-transform-origin: 50% 0%;
	-webkit-transform-origin: 50% 0%; 		
}

@keyframes pullDown {
	0% {
		transform: scaleY(0.1);
	}
	60% {
		transform: scaleY(0.98);
	}
	100% {
		transform: scaleY(1);
	}							
}

@-webkit-keyframes pullDown {
	0% {
		-webkit-transform: scaleY(0.1);
	}
	60% {
		-webkit-transform: scaleY(0.98);
	}
	100% {
		-webkit-transform: scaleY(1);
	}		
}



</style>
<section id="main">

<section>
    <div class="container">
        <div class="card">
            <div class="card-header ch-alt text-center">
                <img class="i-logo" src="" alt="">
            </div>
            <div id="loadCompletoEmail" style="display: none; background: #ffffff8a; position: absolute; width: 100%; height: 100%; top: 0px; left: 0px; z-index: 9999; text-align: center;">
                <div class="loadingio-spinner-ellipsis-vch946vwnpa">
                    <div class="ldio-y7e8hejt6r8">
                        <div></div>
                        <div></div>
                        <div></div>
                        <div></div>
                        <div></div>
                    </div>
                </div>
            </div>
            
                        <div class="col-md-12 divAgendamento" style="text-align: center; ">
                            <h3 class="texto_formulario textBlack my-0">Estamos quase lá!</h3>
                            <h4 class="mt-0 subtituloAgend ">Escolha de o melhor horários que gostaria de fazer seu exame.</h4>
                            <div class="card mt-4">
                                <div class="card-body card-padding" style="padding-top: 0px;">
                                    <div class="gridPage yesFree noTimezone noJumpDate noPeriodButtons" id="gridPage" style="visibility: visible;">
                                        <input type="hidden" name="diaDaSemSelecionado" id="diaDaSemSelecionado" data-content="">
                                        <input type="hidden" value="<?= $this->view->info_user['id']?>" id="idPacient" name="idPacient">
                                        <div role="form" aria-labelledby="formInstructions" class="grid cols7 showTechnicallyFree" style="width: auto; max-width: 800px; margin: 0px auto;">
                                            <?php
                                                $hoje = date('d/m/Y');
                                                $data = DateTime::createFromFormat('d/m/Y', $hoje);
                                                $dats = $data->add(new DateInterval('P1D'));
                                                
                                                $data2 = DateTime::createFromFormat('d/m/Y', $hoje);
                                                $dats2 = $data2->add(new DateInterval('P2D'));
                                                
                                                $data3 = DateTime::createFromFormat('d/m/Y', $hoje);
                                                $dats3 = $data3->add(new DateInterval('P3D'));
                                                
                                                $diaDaSem = $dats->format('D');
                                                $diaDaSem2 = $dats2->format('D');
                                                $diaDaSem3 = $dats3->format('D');
                                                
                                                
                                                switch($diaDaSem){
                                                case 'Mon': $diaDaSem = 'QUA'; $diaDaSem2 = 'QUI'; $diaDaSem3 = 'SEX'; 
                                                    $dats = $data->add(new DateInterval('P2D'));
                                                    $dats2 = $data2->add(new DateInterval('P2D'));
                                                    $dats3 = $data3->add(new DateInterval('P2D'));
                                                break;
                                                case 'Tue': $diaDaSem = 'QUA'; $diaDaSem2 = 'QUI'; $diaDaSem3 = 'SEX'; 
                                                    $dats = $data->add(new DateInterval('P1D'));
                                                    $dats2 = $data2->add(new DateInterval('P1D'));
                                                    $dats3 = $data3->add(new DateInterval('P1D'));
                                                break;
                                                case 'Wed': $diaDaSem = 'QUA'; $diaDaSem2 = 'QUI'; $diaDaSem3 = 'SEX'; 
                                                break;
                                                case 'Thu': $diaDaSem = 'QUI'; $diaDaSem2 = 'SEX'; $diaDaSem3 = 'SEG';
                                                    $dats3 = $data3->add(new DateInterval('P2D')); 
                                                break;
                                                case 'Fri': $diaDaSem = 'SEX'; $diaDaSem2 = 'SEG'; $diaDaSem3 = 'TER';
                                                    $dats2 = $data2->add(new DateInterval('P2D'));
                                                    $dats3 = $data3->add(new DateInterval('P2D'));
                                                break;
                                                case 'Sat': $diaDaSem = 'SEG'; $diaDaSem2 = 'TER'; $diaDaSem3 = 'QUA';
                                                    $dats = $data->add(new DateInterval('P2D'));
                                                    $dats2 = $data2->add(new DateInterval('P2D'));
                                                    $dats3 = $data3->add(new DateInterval('P2D'));
                                                break;
                                                case 'Sun': $diaDaSem = 'TER'; $diaDaSem2 = 'QUA'; $diaDaSem3 = 'QUI';
                                                    $dats = $data->add(new DateInterval('P2D'));
                                                    $dats2 = $data2->add(new DateInterval('P2D'));
                                                    $dats3 = $data3->add(new DateInterval('P2D'));
                                                break;
                                                
                                                }
                                                
                                                $dataHoje = $dats->format('d/m/Y');
                                                $dataAmn = $dats2->format('d/m/Y');
                                                $dataDpsAmn = $dats3->format('d/m/Y');
                                                
                                                ?>
                                            <div class="gridDays my-8 ">
                                                <div class="row mb-8">
                                                    <div class="col-md-12" style="margin-bottom: 30px;">
                                                        <button  class="btn btn-primary waves-effect confirmarAgendamento hide" style="width: 56%;">Confirmar Agendamento</button>
                                                    </div>
                                                    <div class="col-12 mb-3" style="font-size:18px;">
                                                        <h6 id="agendamentoUmRelogio" class="hide" style="color: #00995d;">		<i class="fa fa-clock-o" style="font-size:1rem;"></i><span id="agendamentoUm" 	  data-content=""></span></h6>
                                                        <h6 id="agendamentoDoisRelogio" class="hide" style="color: #00995d;">	<i class="fa fa-clock-o" style="font-size:1rem;"></i><span id="agendamentoDois"   data-content=""></span></h6>
                                                        <h6 id="agendamentoTresRelogio" class="hide" style="color: #00995d;">	<i class="fa fa-clock-o" style="font-size:1rem;"></i><span id="agendamentoTres"   data-content=""></span></h6>
                                                        <h6 id="agendamentoQuatroRelogio" class="hide" style="color: #00995d;">	<i class="fa fa-clock-o" style="font-size:1rem;"></i><span id="agendamentoQuatro" data-content=""></span></h6>
                                                        <h6 id="agendamentoCincoRelogio" class="hide" style="color: #00995d;">	<i class="fa fa-clock-o" style="font-size:1rem;"></i><span id="agendamentoCinco"  data-content=""></span></h6>
                                                    </div>
                                                    <div class="col-4">
                                                        <div class="btnDiaSemana btnDatas" id="data-1" data-input="<?= $dataHoje ?>" data-content="<?= $diaDaSem ?> <?= $dataHoje ?>"><?= $diaDaSem ?></br><?= $dataHoje ?></div>
                                                    </div>
                                                    <div class="col-4">
                                                        <div class="btnDiaSemana btnDatas" id="data-2" data-input="<?= $dataAmn ?>" data-content="<?= $diaDaSem2 ?> <?= $dataAmn ?>"><?= $diaDaSem2 ?></br><?= $dataAmn ?></div>
                                                    </div>
                                                    <div class="col-4">
                                                        <div class="btnDiaSemana btnDatas" id="data-3" data-input="<?= $dataDpsAmn ?>" data-content="<?= $diaDaSem3 ?> <?= $dataDpsAmn ?>"><?= $diaDaSem3 ?></br><?= $dataDpsAmn ?></div>
                                                    </div>
                                                </div>
                                                <input type="hidden" id="horarios">
                                                <input type="hidden" id="horariosId">
                                                <?php for($i = 1; $i <= 3; $i++): ?>
                                                <div class="row hide" id="datas_<?=$i?>" style=>
                                                    <div class="gridDays my-4 ">
                                                        <div class="col-10 offset-1" style=>
                                                            <div class="gridAgendamentoDia row">
                                                                <?php
                                                                    $horariosAgendamento = [    
                                                                        '8:00','8:20','8:40',
                                                                        '9:00','9:20','9:40',
                                                                        '10:00','10:20','10:40',
                                                                        '11:00','11:20','11:40',
                                                                        '13:00','13:20','13:40',
                                                                        '14:00','14:20','14:40',
                                                                        '15:00','15:20','15:40',
                                                                        '16:00','16:20','16:40',
                                                                        '17:00','17:20','17:40'
                                                                    ];
                                                                    
                                                                    foreach($horariosAgendamento as $key => $horario){ 
                                                                    ?>					
                                                                <div class="col-3">
                                                                    <div id="data_<?=$i?>_horario_<?= $key ?>" class="gridSlot gridFree gridAm adicionaHorario removerHorario" value="<?= $horario ?>" data-horario-selecionado="">
                                                                        <a id="button-<?= $horario ?>" aria-labelledby="button-<?= $horario ?> col-header-1" role="button">
                                                                        <?= $horario ?></a>
                                                                    </div>
                                                                </div>
                                                                <?php
                                                                    }
                                                                    ?>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <?php endfor?>
                                                <div style="clear:both;"></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

    <script type="text/javascript">
        jQuery(function ($) {
		
		function exibirAgendamento(data) {
			if($('#datas_'+data).hasClass("hide")){
				$('#datas_'+data).slideDown( 400 ).removeClass('hide').addClass('show');
			} 
		} 

		function removerAgendamento(data) {
			if($('#datas_'+data).hasClass("hide")){
			} else {
				$('#datas_'+data).slideUp( 450 );
				setTimeout(function() {
					$('#datas_'+data).removeClass("show").addClass("hide");
				}, 400);
			}
		}

		$(".btnDatas").click( function()
           {
			var idData = $(this).attr('id');
			idData = idData.split('-');
			idData = idData[1];
			$('#diaSelecionado').val(idData);
			if($('#diaDaSemSelecionado').attr('data-content') == ''){
				$('#diaDaSemSelecionado').attr('data-content',$(this).attr('data-content'));
				$(this).addClass("selected");
				var data = $(this).attr('data-content').split(' ');
				exibirAgendamento(idData);
			}else if($(this).attr('data-content') == $('#diaDaSemSelecionado').attr('data-content')){
					//caso ja esteja selecionado e o proximo clique for p fechar essa data
					$('#diaDaSemSelecionado').attr('data-content','')
					$(this).removeClass("selected");
					removerAgendamento(idData);
			} else	{
				$('#diaDaSemSelecionado').attr('data-content',$(this).attr('data-content'));
				var idDataAntigo = $(".btnDiaSemana.btnDatas.selected").attr("id");
				idDataAntigo = idDataAntigo.split('-');
				idDataAntigo = idDataAntigo[1];
				removerAgendamento(idDataAntigo);
				$(".btnDatas.selected").removeClass("selected");
				$(this).addClass("selected");
				var data = $(this).attr('data-content').split(' ');
				setTimeout(function() {
					exibirAgendamento(idData);
				}, 300);
			}

           }
        );
	  
	 function removerHorario(id,horariosId,horarios){
		if ($("#"+id).hasClass("gridHighlight")){
			$("#"+id).removeClass("gridHighlight");
			arrayHorariosID = JSON.parse(horariosId);
			arrayHorarios = JSON.parse(horarios);
			arrayHorariosID.splice(arrayHorariosID.indexOf(id),1)
			arrayHorarios.splice(arrayHorarios.indexOf($("#"+id).attr('data-horario-selecionado')),1)
			$('#horariosId').val(JSON.stringify(arrayHorariosID) == '[]' ? '' : JSON.stringify(arrayHorariosID)); //store array
			$('#horarios').val(JSON.stringify(arrayHorarios) == '[]' ? '' : JSON.stringify(arrayHorarios)); //store array
			console.log(arrayHorariosID.indexOf(id),1);
			console.log($('#horariosId').val())
			console.log($('#horarios').val())
			atualizarSpanHorario();
			return false;
		}
		return true;
	}

	function atualizarSpanHorario(){
		var horarios = $('#horarios').val();
		horarios = horarios.replace("[","");
		horarios = horarios.replace("]","");
		horarios = horarios.replace(/"/g,"");
		horarios = horarios.split(",");

		_agendamento1 = horarios[0] == undefined ? '' : horarios[0].split(' ');
		_agendamento1 = (_agendamento1[0] == undefined || _agendamento1[1] == undefined) ? '' : ' ' + _agendamento1[0] + ' as ' + _agendamento1[1];
		
		
		$('#agendamentoUm').attr('data-content', _agendamento1);
		
		
		if($('#agendamentoUm').attr('data-content') != '') {
			$('#agendamentoUmRelogio').removeClass('hide');
			$('.confirmarAgendamento').removeClass('hide');
		}else{
			$('#agendamentoUmRelogio').addClass('hide');
			$('.confirmarAgendamento').addClass('hide');
		}

	}


	$( ".adicionaHorario" ).click(function() {

		var id  = $(this).attr("id");
		var horarios = $('#horarios').val();
		var horariosId = $('#horariosId').val();
		var dia = $(".btnDiaSemana.btnDatas.selected").attr("data-input");

		var retorno = removerHorario(id,horariosId,horarios)
		if(!retorno){
			return;
		}

		if(horarios == ""){
			arrayHorarios = [];
		}else{
			var arrayHorarios = JSON.parse(horarios);
		}

		if(horariosId == ""){
			arrayHorariosID = [];
		}else{
			var arrayHorariosID = JSON.parse(horariosId);
		}
		
		if(arrayHorarios.length < 1){
			arrayHorarios.push(dia+" "+$(this).attr("value"));
			arrayHorariosID.push($(this).attr('id'));
			$(this).addClass("gridHighlight").attr('data-horario-selecionado',dia+" "+$(this).attr("value"));
			$('#horarios').val(JSON.stringify(arrayHorarios)); //store array
			$('#horariosId').val(JSON.stringify(arrayHorariosID)); //store array
			// adicionar valor nas divs de exibição
			atualizarSpanHorario();
			
		}else {
			alert("Datas máximas de agendamento atingidas!");
		}

	});

	$(".confirmarAgendamento").on("click", function(event) {
		var horarios = $('#horarios').val();
		var pacient = $('#idPacient').val();
	
		horarios = horarios.replace("[","");
		horarios = horarios.replace("]","");
		horarios = horarios.replace(/"/g,"");
		horarios = horarios.split(",");
		if(horarios.length==0 || horarios == ""){
			alert("Selecione suas datas de agendamento")
			return;
		}
		else if(horarios.length<1){
			alert("Selecione a data de agendamento")
			return;
		}else if (horarios.length > 1){
			alert("Você só pode agendar um dia")
			return;
		}

 
		
		var agendamento = {horarios:horarios,pacient:pacient}
    console.log(agendamento);
	
		$.ajax({
			url: '/register-exame-schedule',
			type: 'POST',
			dataType: 'json',
			data: agendamento,
			async: true
		})
		.done(function (result) {
            console.log(result.status);
            console.log("done");
			if (result.status == "error") {
				event.preventDefault();
				$('#loadCompletoEmail').hide();
			  alert('erro');			}
            event.preventDefault();
			
		})
		.fail(function (p1) {
            console.log("fail");
            console.log(p1);
      
		})
		.always(function () {
            console.log("al");
			event.preventDefault();
		});

    });


});


</script>
