<?=$this->dashboard_patient();?>
<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem;">
      <div class="card-body">


        <div class="row">
          <div class="col">
            <h2>Seu exame foi agendado!</h2><br>

            <h6>Você pode acompanhar o status dele, cancelar ou remarcar.</h6>
          </div>
        </div>

        <div class="row">
          <div class="col">
            <a href="/follow-up-exame?id=<?=$_GET['id']?>" class="btn btn-primary btn-block">Acompanhe seu Exame</a>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>



    
  