<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="vendor/animate/animate.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="vendor/select2/select2.min.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="\css\util.css">
<link rel="stylesheet" type="text/css" href="\css\main.css">
<!--===============================================================================================-->


<?=$this->dashboard_patient();?>
<div class="container">
  <div class="d-flex justify-content-center mt-5" >
    <div class="card cards-geral" style="width: 40rem; ">

       
      <div class="card-body"  style="margin: 5%;">


        <div class="row">
          <div class="col-md-12" style="margin-bottom: 5%;margin-top:5%;">
            <h2>Acompanhamento de Exames</h2><br>
            <hr class="rounded">
          </div>
        </div>

        <div class="row">
          <div class="form-group col-md-6 wrap-input100 validate-input">
              <input type="text" class="input100" value="<?= $this->view->info_exame['name_exame'] ?>" readonly pacheloader name="name" class="form-control" placeholder="Nome do Exame">
              <span class="focus-input100"></span>
                  <span class="symbol-input100">
                    <i class="fa fa-envelope" aria-hidden="true"></i>
              </span>
            </div>
          <div class="form-group col-md-6 wrap-input100 validate-input">
              <input type="text" class="input100" value="<?= $this->view->info_exame['hour'] ?>" readonly pacheloader name="name" class="form-control" placeholder="Nome do Exame">
              <span class="focus-input100"></span>
                  <span class="symbol-input100">
                    <i class="fa fa-clock" aria-hidden="true"></i>
              </span>
            </div>
          <div class="col-md-12" style="margin-top: 10px">
            <a href="/follow-up-exame" class="btn btn-primary btn-block">Remarcar</a>
            <a href="/follow-up-exame" class="btn btn-primary btn-block">Cancelar</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>



    
  