<?=$this->dashboard_patient();?>
<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem;">
      <div class="card-body">


        <div class="row">
          <div class="col">
            <h2>Acompanhamento de Exames</h2><br>
          </div>
        </div>

        <div class="row">
          <div class="form-group col-md-6">
              <input type="text" value="<?= $this->view->info_exame['name_exame'] ?>" readonly pacheloader name="name" class="form-control" placeholder="Nome do Exame">
          </div>
          <div class="form-group col-md-6">
              <input type="text" value="<?= $this->view->info_exame['hour'] ?>" readonly pacheloader name="name" class="form-control" placeholder="Nome do Exame">
          </div>
          <div class="col-md-12">
            <a href="/follow-up-exame" class="btn btn-primary btn-block">Remarcar</a>
            <a href="/follow-up-exame" class="btn btn-primary btn-block">Cancelar</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>



    
  