
<?=$this->dashboard_doctor();?>
<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 70rem;  margin-bottom:10%;">
      <div class="card-body">
        <div class="row">
        <div class="col-md-12">
              <h5> Informação de dados</h5><hr>
              </div>
        </div>

        <div class="row">
          <div class="col">
            
            <form action="" id="save-edit-patient" method="post">
              <input type="hidden" name="id" value="<?= $this->view->info_user['id'] ?>">
            
              <div class="row">
              <div class="form-group col-md-6">
                <input type="text" value="<?= $this->view->info_user['name_doctor'] ?>" readonly pacheloader name="name" class="form-control" placeholder="Nome">
              </div>

              <div class="form-group col-md-6">
                <input type="text" value="<?= $this->view->info_user['email'] ?>"  readonly name="email" class="form-control" placeholder="E-mail">
              </div>

              <div class="form-group col-md-4">
                <input type="text" value="<?= $this->view->info_user['cpf'] ?>" readonly  name="cpf" class="form-control" placeholder="CPF">
              </div>

              <div class="form-group col-md-4">
                <input type="text" value="<?= $this->view->info_user['crm'] ?>" readonly  name="cpf" class="form-control" placeholder="CPF">
              </div>

              <div class="form-group col-md-4">
                <input type="text" value="<?= $this->view->info_user['cellphone'] ?>" readonly name="cellphone" class="form-control" placeholder="Telefone">
              </div>

              <div class="form-group col-md-4">
                <input type="text" value="<?= $this->view->info_user['born_register'] ?>" readonly name="born_register" class="form-control" placeholder="Data de Nascimento">
              </div>
              
              <div class="col-md-12">
              <h5> Endereço </h5><hr>
              </div>
              <div class="form-group col-md-4" >
                <input type="text" value="<?= $this->view->info_user['cep'] ?>" readonly name="cep" class="form-control" placeholder="CEP">
              </div>

              <div class="form-group col-md-4">
                <input type="text" value="<?= $this->view->info_user['citty'] ?>" readonly name="citty" class="form-control" placeholder="Cidade">
              </div>

              <div class="form-group col-md-4">
                <input type="text" value="<?= $this->view->info_user['street'] ?>" readonly  name="street" class="form-control" placeholder="Rua">
              </div>
              
              <div class="form-group col-md-4">
                <input type="text" value="<?= $this->view->info_user['number'] ?>" readonly  name="number" class="form-control" placeholder="Número">
              </div>

              <div class="form-group col-md-4">
                <input type="text" value="<?= $this->view->info_user['district'] ?>" readonly name="district" class="form-control" placeholder="Bairro">
              </div>

              <div class="col-md-6 center">
              <button type="button" id="btn-edit-patient" style="display: block" class="btn btn-primary btn-block">Alterar dados</button>
              <button type="submit" id="btn-save-edit-patient" style="display: none" class="btn btn-primary btn-block">Salvar</button>
             
            </div>
            
            </form>

          </div>
        </div>

      </div>
    </div>
  </div>
</div>

